# aurora
software for processing natural source electromagnetic data 

20210715: Pause
I have change four files:
	modified:   aurora/aurora_driver.py
	modified:   aurora/pipelines/process_mth5.py
	modified:   aurora/sandbox/mth5_helpers.py
	modified:   aurora/sandbox/test_calibration.py

And tests were running before
... 
I want to try saving these four as pyx and re-testing two codes
1. aurora_driver
2. test_calibration

The first should run, and the second on its way

aurora_driver currently runs.


With a single comment out aurora driver works
so why not the other
